server:
  port: 3000

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    password: 123456
    username: admin
    #开启手动确认消费消息
    listener:
      simple:
        acknowledge-mode: manual
